apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubecost-test
spec:
  capacity:
    storage: 32Gi # 32gi 이상으로 해야한다.
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/mnt/data1" # 해당 경로의 권한이 777로 되어 있어야 한다. 소유권은 nobody로 되어 있어야 한다.

