apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubecost-prometheus
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/mnt/data2"

