apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubecost-test
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # PVC와 일치시켜야 함
  hostPath:
    path: "/mnt/data"           # 노드 상 디렉토리

